# Generated by Django 5.2.5 on 2025-10-01 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_student_program_alter_student_studentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.subject'),
        ),
    ]
