# Generated by Django 5.2.5 on 2025-10-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
