# Generated by Django 5.2.5 on 2025-10-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_transaction_time_of_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
